services:
  ollama-vk:
    image: ollama-vulkan:latest
    container_name: ollama-vulkan-whyvl
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    networks:
      - ollama-docker
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    environment:
      - OLLAMA_LLM_LIBRARY=vulkan
    cap_add:
      - CAP_PERFMON
    privileged: true
    group_add:
      - video
      - 39
    volumes:
      - ollama-data:/root/.ollama

volumes:
  ollama-data:

networks:
  ollama-docker:
